### PR TITLE
Issue 347: open contact for editing

### PR DESCRIPTION
**Pull request by mardy**

### CODE REVIEW

**Comment by lduboeuf** [comment]
@mardy i think the test failure issue is already there before your PR, see last merged commit: https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fmessaging-app/detail/xenial/110/pipeline

**Comment by lduboeuf** [comment]
@mardy History-service still uses the old backend, and should explain the contact not found: 
https://gitlab.com/ubports/development/core/history-service/-/blob/main/src/contactmatcher.cpp#L46

**Comment by lduboeuf** [comment]
Also i see that on Dialer app you changed ContactListModel to ContactModel, we have ContactListModel on messaging-app too

**Comment by lduboeuf** [comment]
Installing history-service PR and this PR, we can see now the contact, can edit it. Content is saved but the UI freeze when saving.

**Review by lduboeuf — APPROVED** [review]

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
