### PR TITLE
don't let the draft overwrites already written text

### LINKED ISSUE #232: Draft visible in Thread view but not in conversation
In some cases, e.g forward a message, select a recipient, then go back, the draft is properly displayed in the thread list view.
Now selecting this Thread don't show the draft.
This can also happen by Writing a new message, and then select a recipient.

on Database side it makes the draft having no eventid and thus could not be retrieved later

### LINKED ISSUE #235: new message is overwritten by the draft when selecting a contact
1st case: Forward a message, choose a contact who have a draft, forwarded message text will be overwritten by the draft.
2nd case: Write a new message, then choose a contact, if any draft, the current message will be overwritten by the draft.

### PR DESCRIPTION
**Pull request by lduboeuf**
fixes #232, fixes #235

### CODE REVIEW

**Comment by lduboeuf** [comment]
~~i need to review it~~

**Review by dobey — CHANGES_REQUESTED** [review]
Would be nice to have test coverage of this. Can you add regression tests please?

**Comment by lduboeuf** [comment]
i'm afraid that will be too much work ( for me at least) , i don't see any good example of test for messaging-app to start with.
And this PR add some checkings to avoid errors even if i know it can add regression

**Comment by dobey** [comment]
> i'm afraid that will be too much work ( for me at least) , i don't see any good example of test for messaging-app to start with.
> And this PR add some checkings to avoid errors even if i know it can add regression

The place to start, would be to add a test in `tests/qml/tst_MessagesView.qml` it seems. I can maybe help you in the Telegram chat if you need some mentoring with it. To maintain and improve the quality of UT, we need to have coverage of all the possible code branches, and we need to be more strict about having tests for new features and such.

Thanks.

**Comment by lduboeuf** [comment]
Yeah need to set up my IDE first or env to get tests running.
 But you know Messages.qml is  > 1600 loc, so tests on it will be really hard, there is almost nothing existing about that part. 
Not to mention the fact that messaging app  was designed as a multi protocol app... and most of logic is in javascript.

So. i'm afraid, the time spent to make test on it, could be the time to move things to backend 
( which i can't do with my current skill and time )

**Comment by dobey** [comment]
OK. After looking at this to see if I could help you get some tests added for this, the way things work here seem written in a not very testable manner, and we haven't been using autopilot for things so I'm sure those tests are way outdated too. I'm going to approve and get this merged, but we should really work on getting automated tests working for this stuff. Thanks.

**Review by dobey — APPROVED** [review]
Tests are too complicated to be required in this PR for now, so I"m going to merge without. We really need to get proper automated testing place for all the things under UBports umbrella again. Looks OK otherwise though. Thanks!

**Comment by TellingBerto** [comment]
Device: VollaPhone
Channel: rc
Build: 2020-W43

Result: No issue on VollaPhone.

Steps processed:
1. Create a SMS in message app for a receiver, text: "Test".
2. Don´t send.
3. Message is stored with prefix "Draft", text "Test"
4. Create a new SMS for the previously receiver.
5. Existing SMS is picked up, previous text "Test" is displayed and can be changed to "Test 1".
6. Don´t send.
7. Updated Message is stored with prefix "Draft", text "Test 1"

**Pull request merged**
