### PR TITLE
Manage draft in database

### PR DESCRIPTION
**Pull request by lduboeuf**
Currently, drafts are stored using Settings.
The idea is to reuse existing database and store a message as a draft in the db, so that it can appear in the thread list and manage more easily draft attachments.
NB: attachments are only saved in cache, they does not exist anymore after rebooting

~~To test this feature, https://github.com/ubports/history-service/pull/11 need to be merged or build/deployed before this PR.~~

It is recommended to backup history db before : ` adb pull /home/phablet/.local/share/history-service/history.sqlite history.sqlite` 

screenshot20200211_233316275

Click package available for test here: https://drive.google.com/file/d/1HRbyIjrOSOQXeZ00euIvV8twB4eOTXGq/view?usp=sharing

### CODE REVIEW

**Comment by lduboeuf** [comment]
@maintainers how to convert this PR to a draft ?

**Comment by lduboeuf** [comment]
we need to fix that before : ~~https://github.com/ubports/messaging-app/issues/161~~ as it occurs almost everytime.

**Comment by lduboeuf** [comment]
Update: Will wait for all above PR to be merged before going further and was waiting for a work to be done on History-service, see PR https://github.com/ubports/history-service/pull/25

**Comment by lduboeuf** [comment]
humm found regression on audio recording

**Review by Flohack74 — APPROVED** [review]

**Comment by lduboeuf** [comment]
Beware this could be a OTA-13 blocker, need to have confirmation because my database can be very messy since with all my tests.
I faced several issues:
- The message is effectively sent but still appears as pending.
- Notification of new message is ok but does not appear in the conversation view ( it happens for several contacts but not all)
- Writing a draft triggered a Lomiri reboot

If confirmed, we need to revert that PR

**Comment by farkasdvd** [comment]
Device: bq e5
Image: 2020-W35/2

After creating a draft the listview jumps to the last message and I need to scroll all the way up to find my newly created draft.
I created the following draft:

```
INSERT INTO text_events VALUES('ofono/ofono/account0','111111111','','self','2020-08-29T04:33:01.000Z',0,'test',0,8,'2020-08-29T04:33:01.000Z','',0);
```

When I select the draft it correctly opens but the textfield is empty and the text 'test' is nowhere to be found. I entered a new text 'test2'. The DB now looks like this:

```
INSERT INTO text_events VALUES('ofono/ofono/account0','111111111','','self','2020-08-29T04:33:01.000Z',0,'test',0,8,'2020-08-29T04:33:01.000Z','',0);
INSERT INTO text_events VALUES('ofono/ofono/account0','111111111','2020-08-29T05:15:11.477Z','self','2020-08-29T05:15:11.000Z',0,'test2',0,8,'2020-08-29T05:15:11.000Z','',0);
```

Only the last one is displayed in the listview. After opening it the textfield now contains the text 'test2' correctly. After clearing the textfield the last line disappeared from the DB and the draft preview showed the previous text 'test' but after opening it the textfield was empty.

**Comment by lduboeuf** [comment]
yes draft without recipient is not implemented as it is quite complex to handle.
And having several drafts for the same recipient is not possible too

**Comment by farkasdvd** [comment]
@lduboeuf 
All my drafts have a recipient from my contacts. I just edited the number in my comment. My understanding is that a draft without a recipient is reused when you are creating a new thread.
It makes sense to allow only 1 draft per recipient, however somehow it creates 2 entries in the database.
One more observation: creating a thread with an empty draft is displayed at the end of the listview with no timestamp. It is probably due to the missing entry in the text_events table.
Seems like all these issues are related to drafts in new threads. Drafts in existing threads work fine.

empty_draft

**Comment by lduboeuf** [comment]
oh can't reproduce it.
But i just have an issue when writing a new message and then choose a contact, the draft is stored for the contact ( we can see it in thread list ), but it doesn't displayed in the conversation view. Need to have a look, but can't before Monday

**Comment by jezek** [comment]
There is a cal fo testing, how exactly test this?

Device: FP2
Image: 2020-W35/2

I've tried to write message and not send. Went back to main message conversations page, and the contact with draft was on top and had red ```Draft: message text preview```. After tapping the contact, the draft gets focused. After deleting draft, the contact was as at the beginning. It seems to work as expected.

**Comment by lduboeuf** [comment]
@jezek 
This can be tested by creating a draft, closing the app, go back, send the draft while network disconnect, etc...

**Comment by jezek** [comment]
@lduboeuf tried everything you suggested. No faults spotted. Everything works as expected. Thank you for improving this app.

**Pull request merged**
