### PR TITLE
fix sms/mms wrong display

### LINKED ISSUE #183: Some longer texts extend outside of the text bubble (again)
This bug seems to be back on BQ E5 HD. Seen on dev 488 tonight.
SMS out of box

For information, please note that the actual text of the SMS was long. At least fifteen lines

### PR DESCRIPTION
**Pull request by lduboeuf**
fix overlapping text on conversation list ( MMS text file case ): fixes: https://github.com/ubports/messaging-app/issues/183
fix white space and new lines not preserved: https://github.com/ubports/messaging-app/issues/194

### CODE REVIEW

**Comment by Flohack74** [comment]
Is there a specifci reason you do not want to have this in OTA-12 ?

**Comment by Flohack74** [comment]
Well other way round... Apps are somewhat on a separate cycle and can be updated independently. So there is not that much of a risk to get things broken here. The other question is if the messaging app is a click or a deb install ;)

**Comment by lduboeuf** [comment]
> Is there a specifci reason you do not want to have this in OTA-12 ?

maybe, if we see side effects ?. Hard to know all use cases
> Apps are somewhat on a separate cycle and can be updated independently

Oh i didn't know  messaging app can be shipped independently without OTA update

**Comment by lduboeuf** [comment]
click test here: https://drive.google.com/file/d/1HRbyIjrOSOQXeZ00euIvV8twB4eOTXGq

**Review by Flohack74 — APPROVED** [review]

**Comment by AppsLee** [comment]
Device: Nexus 5
Image: 2020-W35/2

I had this issue and identified few text messages.
Now the bubble are fine as expected.

**Comment by jezek** [comment]
Device: FP2
Image: 2020-W35/2

Works.
Tested with multi line sms and mms and looked through multiple conversations. Nothing as described in the 2 issues (#183 #194) was spotted.

**Comment by lduboeuf** [comment]
yes still an issue when having audio message, long press on it don't trigger multi-select view, but could be for another PR  for OTA-14

**Pull request merged**
