### PR TITLE
UbuntuColors to theme, bumped version

### PR DESCRIPTION
**Pull request by cibersheep**
- UbuntuColors to theme palette counterparts
- QtQuick Bumped version
- Only main action button colored
- Clear text on button actions

### CODE REVIEW

**Comment by cibersheep** [comment]
- Update pot

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
Please also adapt the tests:
```
2: FAIL!  : QmlTests::messageBubbleTestCase::test_changeIncomingMustUpdateSource() Compared values are not the same

2:    Actual   (): #0e8420

2:    Expected (): green

2:    Loc: [/build/varlibjenkinsworkspacemessagingappPRmessagingappubportsgbpbadsc/tests/qml/tst_MessageBubble.qml(89)]

2: QWARN  : QmlTests::messageBubbleTestCase::test_changeIncomingMustUpdateSource() file:///build/varlibjenkinsworkspacemessagingappPRmessagingappubportsgbpbadsc/tests/qml/tst_MessageBubble.qml:50:5: QML MessageBubble: Cannot open: file:///build/varlibjenkinsworkspacemessagingappPRmessagingappubportsgbpbadsc/src/qml/assets/#ffffff_bubble.sci

2: FAIL!  : QmlTests::messageBubbleTestCase::test_incomingMessageBubbleMustUseIncomingSource() Compared values are not the same

2:    Actual   (): #ffffff

2:    Expected (): white

2:    Loc: [/build/varlibjenkinsworkspacemessagingappPRmessagingappubportsgbpbadsc/tests/qml/tst_MessageBubble.qml(76)]

2: FAIL!  : QmlTests::messageBubbleTestCase::test_outgoingMessageBubbleMustUseOutgoingSource() Compared values are not the same

2:    Actual   (): #0e8420

2:    Expected (): green

2:    Loc: [/build/varlibjenkinsworkspacemessagingappPRmessagingappubportsgbpbadsc/tests/qml/tst_MessageBubble.qml(82)]

2: PASS   : QmlTests::messageBubbleTestCase::cleanupTestCase()

2: Totals: 2 passed, 3 failed, 0 skipped, 0 blacklisted, 2ms

2: ********* Finished testing of QmlTests *********

2/5 Test #2: MessageBubble ....................***Failed    3.88 sec
```

**Comment by cibersheep** [comment]
Ouh. I'll do. Thanks

**Comment by cibersheep** [comment]
Done

**Pull request merged**
