### PR TITLE
Re-enable Swipe Demo

### LINKED ISSUE #300: Demo on message not working anymore
When on first time run, when in conversation view, the demo does not display animations for swipe actions.

### PR DESCRIPTION
**Pull request by lduboeuf**
fixes #300 
To test, edit `~/.config/com.ubuntu.messaging-app/MessagingApp.conf` and set `hintNecessary` to `true` and either send a message or just go to the conversation view

Click test package available here: arm64: https://github.com/lduboeuf/messaging-app/suites/4814619336/artifacts/135579936
armhf: https://github.com/lduboeuf/messaging-app/suites/4814619336/artifacts/135579937

### CODE REVIEW

**Comment by lduboeuf** [comment]
~~humm, on desktop, demo is shown on the thread left page~~

**Comment by UniversalSuperBox** [comment]
image

I think the variance of fades looks a little silly, and the "Got it" text is hard to read. Should we change that?

**Comment by lduboeuf** [comment]
Humm don't see where is the issue. I've only took the example from dialer-app swipe demo

**Comment by UniversalSuperBox** [comment]
To me, it seems strange that the header and editing bar don't fade. If you think it's okay, then whatever.

**Comment by lduboeuf** [comment]
@UniversalSuperBox i removed the header and the composeBar. Let see if it is better

**Comment by Flohack74** [comment]
Can you check translations pot to be sure nothing has changed?

**Comment by lduboeuf** [comment]
@Flohack74 should be good now

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
