### PR TITLE
Rewriting of Draft management

### PR DESCRIPTION
**Pull request by lduboeuf**
This is a  rewriting of the Draft, just to explore other way to do that, and maybe fix more easily the random issues we face with draft 
Did some moves to avoid some bottom up dependencies.
As onStateChanged from Qt.application seems to be correctly fired, we only save draft when applicaton is not active and when the component is destroyed, this will save a Timer and unneeded saves

### CODE REVIEW

**Comment by lduboeuf** [comment]
I've tried to use `crossbuilder` for building `messaging-app` but with no luck , there are broken dependencies. If anyone can point me how to build and deploy for testing the deb, would be great

**Comment by lduboeuf** [comment]
can someone help me with crossbuilder, i have this:
```
dh_install
dh_install: messaging-app-autopilot missing files: usr/lib/python*/dist-packages/messaging_app/*
dh_install: messaging-app-autopilot missing files: usr/lib/python*/dist-packages/messaging_app/testdata/*
dh_install: missing files, aborting
debian/rules:48: recipe for target 'override_dh_install' failed
make[1]: *** [override_dh_install] Error 2
make[1]: Leaving directory '/home/lduboeuf/messaging-app'
debian/rules:24: recipe for target 'binary' failed
make: *** [binary] Error 2
```

**Comment by lduboeuf** [comment]
ok, disbabled autopilot tests... but would be nice for beginners to have a workaround :)

**Comment by lduboeuf** [comment]
I've just realized that for testing the deb, i do not need crossbuilder, as CI will build it for me on Ubports repo... and be able to install it with ubports-qa later...

**Comment by lduboeuf** [comment]
may fix https://github.com/ubports/messaging-app/issues/136

**Comment by Flohack74** [comment]
We should try to keep alive tests as much as possible, since we already now have a very bad test coverage. Maybe @dobey can help with fixing this.

**Comment by lduboeuf** [comment]
> We should try to keep alive tests as much as possible, since we already now have a very bad test coverage. Maybe @dobey can help with fixing this.

Does it mean that CI bot doesn't play tests ?
I did not had success locally with crossbuilder

**Comment by Flohack74** [comment]
The CI should run all tests, if there are any.

**Comment by lduboeuf** [comment]
> The CI should run all tests, if there are any.

oh ok, so seems that there is no regression for my PR

**Comment by Flohack74** [comment]
Are the tests still disabled in the latest commit? I do not find test results in the CI log.

**Comment by lduboeuf** [comment]
humm didn't do anything regarding that

**Comment by lduboeuf** [comment]
please do not merge, i've missed something when refactoring

**Comment by lduboeuf** [comment]
ok, finally i've reverted part of modifications done, this may not have side effects now

**Comment by Flohack74** [comment]
and now unfortunately you need to resolve conflicts ;)

**Comment by lduboeuf** [comment]
remove the timer and only save draft on active change and component destruction.
Be able now to save draft on new message, fix https://github.com/ubports/messaging-app/issues/124

**Comment by Flohack74** [comment]
Ok I can review this. You got 3 PRs open, do you want a certain order for the merge? Can they conflict?

**Comment by lduboeuf** [comment]
@Flohack74 , humm except for translation i guess, it seems not, would you like me to merge all in one PR ?
Or we can start by that one first ( the oldest ) and then i will update others PRs

**Comment by Flohack74** [comment]
No, they should stay separate: 1 feature = 1 PR ;) yes lets start from here...

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
