### PR TITLE
Fix div width that causes display problems for text/plain MMS.

### PR DESCRIPTION
**Pull request by gwado**
Issue mentioned here: #128

### CODE REVIEW

**Comment by Flohack74** [comment]
Is this the fix for #110 ?

**Comment by gwado** [comment]
Sorry, for #128

**Comment by gwado** [comment]
> Is this the fix for #110 ?

For #128. But certainly for #110 too, because i can suppose that's the same problem (MMS text).

**Comment by krille-chan** [comment]
Hey, this leads to another problem: All messagebubbles will have the same maximum width even if the messages are very short:
screenshot20190908_093348625

**Comment by gwado** [comment]
@ChristianPauly 
Ok, thus, i suppose that we can pass a type variable in message to know if it's a MMS.PlainText or other and adapt the width.
I will see that.

**Comment by gwado** [comment]
@ChristianPauly It's ok now. :)
Just adapt width. Not pass type variable or other complex thing.

**Comment by krille-chan** [comment]
> @ChristianPauly It's ok now. :)
> Just adapt width. Not pass type variable or other complex thing.

I've tested and it seems to work very well now. LGTM thank you very much

**Comment by UniversalSuperBox** [comment]
@gwado, is there any specific way you would like to be credited in our changelog for our next release? Would you prefer your username, the real name you have set on GitHub...?

For an example, see the changelog at https://ubports.com/blog/ubports-blog-1/post/call-for-testing-ubuntu-touch-ota-10-238

**Comment by gwado** [comment]
Real name, Raphaël Fery, is good.
Thanks! :)

On Sun, 8 Sep 2019 12:16:34 -0700, Dalton Durst wrote:
> @gwado, is there any specific way you would like to be credited 
> in our changelog for our next release? Would you prefer your 
> username, the real name you have set on GitHub...?
>
> For an example, see the changelog at 
> https://ubports.com/blog/ubports-blog-1/post/call-for-testing-ubuntu-touch-ota-10-238
>

--

**Comment by UniversalSuperBox** [comment]
Well, thank you! I see this is your first PR on GitHub, congratulations! Do you have any questions about the project, or is there something else I can help you with within (or without) UBports?

**Comment by gwado** [comment]
> Well, thank you! I see this is your first PR on GitHub, congratulations! Do you have any questions about the project, or is there something else I can help you with within (or without) UBports?

Thank you for your help.
It's nice to have a system in which you can participate and help. However, I have questions about the security of our personal data because the project seems fragile to me because of a lack of human resources (and I don't have the skills to help).
And the battery of my nexus 5 is draining very quickly, but this is a problem already identified by others.

**Comment by UniversalSuperBox** [comment]
For the Nexus 5, I'd suggest looking into replacing your device's battery. It really helps. Batteries can be had for fairly cheap, I bought a new old stock on iFixit.

For security, I recognize that we are a small team and, due to using old device kernels and builds of Android, have unpatched holes. I'll let you make your own decision on whether that's acceptable for you.

**Comment by UniversalSuperBox** [comment]
Also if you're in the continental US, I'd love to get some stickers to you as thanks. Hit me up @UniversalSuperBox on Telegram or dalton@ubports.com.

**Comment by gwado** [comment]
> For the Nexus 5, I'd suggest looking into replacing your device's battery. It really helps. Batteries can be had for fairly cheap, I bought a new old stock on iFixit.
> 
> For security, I recognize that we are a small team and, due to using old device kernels and builds of Android, have unpatched holes. I'll let you make your own decision on whether that's acceptable for you.

Thank you for your answer.
I dropped UT and smartphones in general.
My nexus 5 could run Android 9 with a custom rom. This means that the equipment is powerful enough. But Google does not provide an update....
And using a custom rom built by a stranger seems dangerous to me for my personal data.

The same is true for UT, which is a very beautiful project, but whose team is not sufficient to ensure relative safety.

And I can't help, I don't have the skills or the time, unfortunately.

The world of smartphones saddens me. While it is the most widely used tool and contains so much personal data.

I went back to my touch-tone phone.

**Pull request merged**
