### PR TITLE
Fix error on property enableAttachments reading 

### PR DESCRIPTION
**Pull request by lduboeuf**

### CODE REVIEW

**Review by Flohack74 — APPROVED** [review]

**Comment by ivoxavier** [comment]
So in this first OTA-24 RC, the #278 is fixed on the Oneplus 6T(no icons when MMS is disabled) but in my fairphone2 in RC channel the icons persist.

**Comment by lduboeuf** [comment]
> So in this first OTA-24 RC, the #278 is fixed on the Oneplus 6T(no icons when MMS is disabled) but in my fairphone2 in RC channel the icons persist.

Just to b sure, can you compare messaging-app version between the two devices ?.
e.g: ` apt list messaging-app`

**Comment by ivoxavier** [comment]
6T : `0.1.3~0ubports0+0~20220725155755.106~1.gbp0d0303 arm64 [installed,local]`
FP2 : `0.1.3~0ubports0+0~20220725155755.106~1.gbp0d0303 armhf [installed,local]`

**Comment by lduboeuf** [comment]
> 6T : `0.1.3~0ubports0+0~20220725155755.106~1.gbp0d0303 arm64 [installed,local]` FP2 : `0.1.3~0ubports0+0~20220725155755.106~1.gbp0d0303 armhf [installed,local]`

So that is really weird...
How can there be a difference between the two device... MMS toggle is just a setting property. Will dig more when back home

**Pull request merged**
