### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by ubports-weblate**
Translations update from [Weblate](https://translate.ubports.com/projects/ubports/messaging-app/) for UBports/messaging-app.

### CODE REVIEW

**Comment by dobey** [comment]
Why are there backup `.po~` files being added in this? @Flohack74 ?

**Comment by Flohack74** [comment]
No idea will remove it

**Comment by dobey** [comment]
> No idea will remove it

Any chance you can fix this? Would like to get this merged before we freeze for the OTA.

**Comment by Flohack74** [comment]
Yes weekend is a good time for this

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
