### PR TITLE
Fix SMS counter

### PR DESCRIPTION
**Pull request by krille-chan**
screenshot20190405_154308539

### CODE REVIEW

**Comment by Danfro** [comment]
Testing on E5 with RC 2019-W18.

Counter does appear at 10 chars before the end of the first SMS. :+1:

**Comment by jezek** [comment]
FP2 (2019-W18)

Counter does appear at 10 chars before the end of the first SMS.

**Comment by ziggutas** [comment]
BQ E4.5 rc (2019-W18)
Cannot see a message counter despite repeated attempts at composing a message.

**Comment by krille-chan** [comment]
> BQ E4.5 rc (2019-W18)
> Cannot see a message counter despite repeated attempts at composing a message.

The counter appears at 10 chars before the end of the first SMS. Have you tried to write more characters?

**Comment by ziggutas** [comment]
I write about 3 lines of text and nothing appears.
Continue message, add emojis and on about the 10th emoji a number such as '10/1' may appear.
No bracketed number as in your screenshot example above.
Another test writing 1.5 lines text followed by emojis needed 19 emojis before anything showed under text box.

**Comment by krille-chan** [comment]
The behaviour changed in latest merge request. Only when there are 10 characters left for 1 sms, it is visible. That's the same behaviour like on the android sms app.

**Comment by ziggutas** [comment]
Ahhh, I hadn't grasped exactly what this issue was, excuse my confusion
!!
BQ E4.5 works fine.
Counter appears for last 10 characters of first message and then changes to '145/2', presumably counting down for the second message.
And I now notice emojis are equivalent to 5 characters, I think.
Nifty.

**Pull request merged**
