### PR TITLE
Be able to undo a delete action

### LINKED ISSUE #321: feature request: put a timed undo delete button to prevent people from deleting all messages of a one contact by accident
Like in the "Dekko"-app I suggest putting in a timed undo button in the messaging-app of ubuntu touch. Some silly people like me sometimes swipe by accidentone of their contacts to the right and then press the delete-button. If there were an undo button ore a question like: do you really want to delete the messaging history of this contackt? this might be very helpful.

### PR DESCRIPTION
**Pull request by lduboeuf**
fixes #321 
screenshot20220202_115215038

Click test package available here: https://github.com/lduboeuf/messaging-app/actions , choose the last Build and artefact below

### CODE REVIEW

**Comment by peat-psuwit** [comment]
This seems to have UI change. Could you please attach screenshot(s) for this?

**Comment by lduboeuf** [comment]
> This seems to have UI change. Could you please attach screenshot(s) for this?

see first comment ^

**Comment by peat-psuwit** [comment]
Err... if I understand correctly:
- The user press delete. The thread disappears in the UI, and the button appears.
- After a while the button will disappear and the thread will be actually deleted from backend.

In this case, the text should be "(n) thread(s) deleted" instead of "(n) thread(s) to delete". Because UI wise, it's been deleted.

**Comment by lduboeuf** [comment]
@peat-psuwit 


> Err... if I understand correctly:
> 
>     * The user press delete. The thread disappears in the UI, and the button appears.

No, the Thread is still visible while the undo section is visible


> 
>     * After a while the button will disappear and the thread will be actually deleted from backend.
> 
Yes

> 
> In this case, the text should be "(n) thread(s) deleted" instead of "(n) thread(s) to delete". Because UI wise, it's been deleted.

**Comment by peat-psuwit** [comment]
Ok. IMO it's a bit weird to have things still visible after pressing delete, and then disappear after a moment. Also "Undo" implies that something has already happened. The way I thought at first feels better. 

Another possible way is to make delete multi-selectable e.g. after selecting delete, UI changes to multi-select mode where one can select multiple threads, and then confirm again to delete.

@cibersheep, may I have your input on this one?

**Comment by cibersheep** [comment]
If I read this correctly:
- Select or delete message
- Top message appears with the undo button
- If undo is pressed, the messages will not be deleted
- If nothing happens, messages are deleted.

I assume in the code the messages are not deleted until this warning is gone, but as a user the deletion is triggered except you undo it.
I would say: 
- x message(s) deleted [undo] or
- x message(s) about to be deleted [cancel]

**Comment by lduboeuf** [comment]
> Ok. IMO it's a bit weird to have things still visible after pressing delete, and then disappear after a moment. Also "Undo" implies that something has already happened. The way I thought at first feels better.

Yes, i was trying to make a "disabled" style when clicking on the delete button, but that is not possible due to the way the component ListItemWithActions behaves. But it is the case when delete an individual item by swiping.

**Comment by cibersheep** [comment]
> Yes, i was trying to make a "disabled" style when clicking on the delete button, but that is not possible due to the way the component ListItemWithActions behaves. But it is the case when delete an individual item by swiping.

Isn't it possible to add `enabled: [variable when deleting is ongoing]` to the actual Button?
https://github.com/ubports/messaging-app/pull/322/files#diff-552d638ea2ddda91a9842345ea2a1e92225d7d50ca2c71eb7f882827f3458f1bR98

**Comment by lduboeuf** [comment]
> Isn't it possible to add `enabled: [variable when deleting is ongoing]` to the actual Button? https://github.com/ubports/messaging-app/pull/322/files#diff-552d638ea2ddda91a9842345ea2a1e92225d7d50ca2c71eb7f882827f3458f1bR98

Yes it is possible, but i was talking about the item being deleted. I haven't find a way to make the item with disabled style like it does for individual deletion

Capture d’écran de 2022-03-04 13-47-22

**Comment by cibersheep** [comment]
> [...] i was talking about the item being deleted. I haven't find a way to make the item with disabled style like it does for individual deletion

Ah, silly me. Sorry.
I'm sure there is a way but not very easy to do. I try to find an example

**Comment by lduboeuf** [comment]
i found a way, but that need to add conditions on properties: e.g color: selectedForDeletion ? .... : ...

**Comment by cibersheep** [comment]
> i found a way, but that need to add conditions on properties: e.g color: selectedForDeletion ? .... : ...

I may not understand what you are doing, but on the `ListItem {}` you should be able to include a `enabled: [variable being deleted]` and lomiri should take care of the colors (deleted is a state in the theme)

enabled: false
imatge

enabled: true
imatge

**Comment by lduboeuf** [comment]
thx i see yes, but sadly the Thread Item is a ListItemWithActions, which in fact is not a ListItem. There is a enabled property, but doesn't do anything

**Comment by cibersheep** [comment]
Sorry I don't know the component. Is this a custom element? If so, must be a way of checking the bool variable

**Comment by cibersheep** [comment]
Is this one?
https://gitlab.com/ubports/core/address-book-app/-/blob/main/src/imports/Lomiri/Contacts/ListItemWithActions.qml

I don't know if an `Item {}` can has the property `enabled` I guess so, but indeed it would need more work that I told you.
Even though, the changes would be OS wide...

**Comment by lduboeuf** [comment]
> Is this one? https://gitlab.com/ubports/core/address-book-app/-/blob/main/src/imports/Lomiri/Contacts/ListItemWithActions.qml

Yes, that one

>I don't know if an Item {} can has the property enabled I guess so, but indeed it would need more work that I told you.
>Even though, the changes would be OS wide...

Yes it have the "enabled" property. That can be interesting to have, but shouldn't that component land on lomiri toolkit rather than staying in Contact lib ? . It is used in dialer-app also...

**Comment by lduboeuf** [comment]
@cibersheep Meanwhile i can do that disabled style for that case in messaging-app directly

**Comment by cibersheep** [comment]
> @cibersheep Meanwhile i can do that disabled style for that case in messaging-app directly

You know the code :) so, I trust you ;)

> Yes it have the "enabled" property. That can be interesting to have, but shouldn't that component land on lomiri toolkit rather than staying in Contact lib ? . It is used in dialer-app also...

Indeed I think we should move it (and maybe use the most modern elements in the toolkit) or update the ListItemLayout to use the actions and style from the contact lib...

**Comment by lduboeuf** [comment]
that should be better now. Items are in "disabled" style while being deleted

**Comment by cibersheep** [comment]
Do you want to test it ^__^ 
Should be via `ubport-qa`, right?

**Comment by lduboeuf** [comment]
> Do you want to test it ^__^ Should be via `ubport-qa`, right?

Yes

**Comment by lduboeuf** [comment]
Well, animation is not very good. Maybe a classic confirmation
 popup like @peat-psuwit said will be better

**Comment by peat-psuwit** [comment]
Huh? I suggested classic popup? I guess that works too, but that's not what I said?

**Comment by lduboeuf** [comment]
> Huh? I suggested classic popup? I guess that works too, but that's not what I said?

oups, i re-read your posts, idk why i was thinking you talked about a popup ;-)

**Comment by lduboeuf** [comment]
i close this in favour of #334.

The "undo" temporary display don't play well regarding animations and add some useless complications in code,

**Pull request closed without merging**
