### PR TITLE
Load messages on  contact selection

### PR DESCRIPTION
**Pull request by lduboeuf**
This allow to load message list (if any) after selecting a contact in new message view and after clicking message icon on address-book-app contact view
(First commit refers to a //FIXME found in code for lazy loading new message view at startup, i can move it from here if needed)

### CODE REVIEW

**Comment by lduboeuf** [comment]
oups still not good for adding, remove, adding, ...

**Comment by lduboeuf** [comment]
ok that's fine now

**Comment by lduboeuf** [comment]
what should be the behavior when selecting multiple contacts ?. When selecting the first, we have the message list, but now after the second selected, should the list be emptyed ?

**Comment by lduboeuf** [comment]
do not merge, have a binding loop after updating the model (after adding > 1 participant )

**Comment by lduboeuf** [comment]
ok, i load message history only when there is a single participant, otherwise, header will change and not able to add/remove a participant

**Comment by lduboeuf** [comment]
TODO: if Draft change PR is merged, don't forget to handle Draft and contact selection for new message as it will erase the current draft

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
