### PR TITLE
Various spelling

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by UniversalSuperBox** [comment]
Interesting. I wonder if any of this code is live in the app? @ChristianPauly, are you sure?

**Comment by comradekingu** [comment]
It just landed on Weblate, so it is assumedly new.

**Comment by krille-chan** [comment]
Some of the strings are from Canonicals idea to integrate IRC support. So the strings are deprecated. But others are in the app.
Thanks for your contribution. I would like to merge your request but I first need to find out why the checks are failing.

**Comment by krille-chan** [comment]
@comradekingu The default branche of this repository is the xenial branche and not master. Could you open your pull request to the xenial branche and close this one?

**Comment by krille-chan** [comment]
It looks like your pull request is now merging translation files from the master branche. This should be done by weblate only to avoid format issues...

**Comment by Flohack74** [comment]
Sorry to reject this but you are only allowed to change to pot file, in order to not create merge conflicts with Weblate.

**Pull request closed without merging**
