### PR TITLE
fix #4 :Dual sim account name 

### LINKED ISSUE #4: Show on which number an SMS has been received
Go to a message in the messaging app, swipe to the side and click on the "i" to get the details of the message. The second information is "from" (I think so, I'm translating the "de" of the french) and the third is "to" (="à"). 
If you have sent the message: in the 2nd information you see "yourself" (=Moi-même)
If you received the message: in the 3rd information you see "yourself"
What I expect to see: a phone number!
I think that's important, because the phone I'm using (BQ E4.5) is double SIM and it's important to know with which SIM I have sent the message because I have two different numbers. In addition if you change the SIM card it's still yourself, but it's not the same phone number!
I don't know if it's really interesting to know in this information list if it's yourself that wrote the message, since to accede to the list you have to see the message and there is a color code (green for written messages, white for received messages)

### PR DESCRIPTION
**Pull request by lduboeuf**
This is to avoid confusion when having dual Sim, for instance only "Myself" is displayed but not which  account name was used to send or received the sms.

ref issue https://github.com/ubports/messaging-app/issues/4

### CODE REVIEW

**Comment by lduboeuf** [comment]
That one has no side effect with previous PR, should be fine.
Note that this PR include another improvement (see first commit )

**Comment by Flohack74** [comment]
Update translation went wrong somehow, I cant see any changes

**Comment by lduboeuf** [comment]
@Flohack74 where do you see conflict in translation ?

**Comment by Flohack74** [comment]
Sorry for the confusion I meant I dont see new strings to translate. But "Myself" was already there, I did not see this. So yes its good to merge.

**Review by Flohack74 — APPROVED** [review]

**Pull request merged**
